import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  let sales = 123_456_789;
  let course: string = 'TypeScript';
  let is_published: boolean = true;

  function render(document: any) {
    console.log(document);
  }
  // Tuple fixed length array- good for key value pairs
  let user: [number, string] = [1, 'Oscar'];

  // Enum list of related constants
  const small = 1;
  const medium = 2;
  const large = 3;

  // PascalCase
  const enum Size {
    Small = 1,
    Medium,
    Large,
  }

  let mySize: Size = Size.Medium;

  // console.log(Size);

  // Question mark is optional
  function calculateTax(income: number, taxYear = 2022): number {
    if (taxYear <= 2022) return income * 1.2;
    return income * 1.3;
  }

  console.log(calculateTax(10_000));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}></div>
      </main>
    </>
  );
}
