import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import useSwr from 'swr';
const inter = Inter({ subsets: ['latin'] });
import Test from '@/components/Test';
import NewTest from '@/components/NewTest';

const fetcher = (url: string) => fetch(url).then((res) => res.json());

export default function Home() {
  // const {data, error, isLoading } => useSwr<{name: string}[]/>('/api/hello', fetcher)
  // if (error) return <div>Failed to load</div>
  // if (isLoading) return <div>Loading...</div>
  // if (!data) return null
  type Quantity = 50 | 100;
  let quantity: Quantity = 100;

  function greet(name: string | null) {
    if (name) console.log(name.toUpperCase());
    else console.log('Hola');
  }
  greet(null);

  let sales = 123_456_789;
  let course: string = 'TypeScript';
  let is_published: boolean = true;

  function render(document: any) {
    console.log(document);
  }
  // Tuple fixed length array- good for key value pairs
  let user: [number, string] = [1, 'Oscar'];

  // Enum list of related constants
  const small = 1;
  const medium = 2;
  const large = 3;

  // PascalCase
  const enum Size {
    Small = 1,
    Medium,
    Large,
  }

  let mySize: Size = Size.Medium;

  // console.log(Size);

  // Question mark is optional variable
  function calculateTax(income: number, taxYear = 2022): number {
    if (taxYear <= 2022) return income * 1.2;
    return income * 1.3;
  }
  // readonly cant be over written
  let employee: {
    readonly id: number;
    name: string;
    retire: (date: Date) => void;
  } = {
    id: 1,
    name: 'Oscar',
    retire: (date: Date) => {
      console.log(date);
    },
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Test title={'Hello world'} subtitle={'Its me'} />
          <NewTest name="Oscar" age={12} />
        </div>
      </main>
    </>
  );
}
